import { layerTemplates } from "@/@types/types";

const Templates: layerTemplates = {
  be9: {
    id: "be9",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 9",
    value: "big_ue_ender_full_gothic_W17_L9",
    width: 17,
    height: 9,
    critical: false,
    nakaOnly: false,
  },
  be10_1: {
    id: "be10_1",
    commands: ["big", "ender", "full"],
    pos: "naka",
    text: "big ender 10 流",
    value: "big_naka_ender_full_gothic_W17_L10_流",
    width: 17,
    height: 10,
    critical: false,
    nakaOnly: true,
  },
  be10_2: {
    id: "be10_2",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 10 臨",
    value: "big_ue_ender_full_gothic_W18_L10_臨",
    width: 18,
    height: 10,
    critical: true,
    nakaOnly: false,
  },
  be11: {
    id: "be11",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 11 臨",
    value: "big_ue_ender_full_gothic_W20_L11_臨",
    width: 20,
    height: 11,
    critical: true,
    nakaOnly: false,
  },
  be12: {
    id: "be12",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 12 臨",
    value: "big_ue_ender_full_gothic_W22_L12_臨",
    width: 22,
    height: 12,
    critical: true,
    nakaOnly: false,
  },
  be13: {
    id: "be13",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 13 臨",
    value: "big_ue_ender_full_gothic_W25_L13_臨",
    width: 25,
    height: 13,
    critical: true,
    nakaOnly: false,
  },
  be15: {
    id: "be15",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 15 臨",
    value: "big_ue_ender_full_gothic_W29_L15_臨",
    width: 29,
    height: 15,
    critical: true,
    nakaOnly: false,
  },
  be16: {
    id: "be16",
    commands: ["big", "ender", "full"],
    pos: "ue",
    text: "big ender 16 臨",
    value: "big_ue_ender_full_gothic_W31_L16_臨",
    width: 31,
    height: 16,
    critical: true,
    nakaOnly: false,
  },
  b16: {
    id: "b16",
    commands: ["big", "full"],
    pos: "ue",
    text: "big 16",
    value: "big_ue_full_gothic_W34_L16",
    width: 34,
    height: 16,
    critical: false,
    nakaOnly: false,
  },
  b17: {
    id: "b17",
    commands: ["big", "full"],
    pos: "naka",
    text: "big 17 流",
    value: "big_naka_full_gothic_W34_L17_流",
    width: 34,
    height: 17,
    critical: false,
    nakaOnly: true,
  },
  me14: {
    id: "me14",
    commands: ["medium", "ender", "full"],
    pos: "ue",
    text: "medium ender 14",
    value: "medium_ue_ender_full_gothic_W25_L14",
    width: 25,
    height: 14,
    critical: false,
    nakaOnly: false,
  },
  me15: {
    id: "me15",
    commands: ["medium", "ender", "full"],
    pos: "naka",
    text: "medium ender 15 流",
    value: "medium_naka_ender_full_gothic_W24_L15_流",
    width: 24,
    height: 15,
    critical: false,
    nakaOnly: true,
  },
  me19: {
    id: "me19",
    commands: ["medium", "ender", "full"],
    pos: "ue",
    text: "medium ender 19 臨",
    value: "medium_ue_ender_full_gothic_W34_L19_臨",
    width: 34,
    height: 19,
    critical: true,
    nakaOnly: false,
  },
  m26: {
    id: "m26",
    commands: ["medium", "full"],
    pos: "ue",
    text: "medium 26",
    value: "medium_ue_full_gothic_W40_L26",
    width: 40,
    height: 26,
    critical: false,
    nakaOnly: false,
  },
  m27: {
    id: "m27",
    commands: ["medium", "full"],
    pos: "naka",
    text: "medium 27 流",
    value: "medium_naka_full_gothic_W40_L27_流",
    width: 40,
    height: 27,
    critical: false,
    nakaOnly: true,
  },
  s21: {
    id: "s21",
    commands: ["small", "ender", "full"],
    pos: "ue",
    text: "small ender 21",
    value: "small_ue_ender_full_gothic_W37_L21",
    width: 37,
    height: 21,
    critical: false,
    nakaOnly: false,
  },
  s22: {
    id: "s22",
    commands: ["small", "ender", "full"],
    pos: "naka",
    text: "small ender 22 流",
    value: "small_naka_ender_full_gothic_W37_L22_流",
    width: 37,
    height: 22,
    critical: false,
    nakaOnly: true,
  },
  s38: {
    id: "s38",
    commands: ["small"],
    pos: "ue",
    text: "small 38",
    value: "small_ue_gothic_W46_L38",
    width: 46,
    height: 38,
    critical: false,
    nakaOnly: false,
  },
  s39: {
    id: "s39",
    commands: ["small"],
    pos: "naka",
    text: "small 38",
    value: "small_naka_gothic_W46_L39_流",
    width: 46,
    height: 39,
    critical: false,
    nakaOnly: true,
  },
  m22: {
    id: "m22",
    commands: ["medium", "full"],
    pos: "shita",
    text: "medium shita W50",
    value: "medium_shita_full_gothic_W50_C22",
    width: 50,
    height: 22,
    critical: true,
    nakaOnly: false,
  },
  s18_1: {
    id: "s18_1",
    commands: ["small", "full"],
    pos: "ue",
    text: "small ue W37 L2",
    value: "small_ue_full_gothic_W37_L2_C9",
    width: 37,
    height: 18,
    critical: false,
    nakaOnly: false,
  },
  s18_2: {
    id: "s18_2",
    commands: ["small", "full"],
    pos: "shita",
    text: "small shita W37 L2",
    value: "small_shita_full_gothic_W37_L2_C9",
    width: 37,
    height: 18,
    critical: false,
    nakaOnly: false,
  },
  s31: {
    id: "s31",
    commands: ["small"],
    pos: "ue",
    text: "small ue W54",
    value: "small_ue_gothic_W54_C31",
    width: 54,
    height: 31,
    critical: true,
    nakaOnly: false,
  },
  ts38: {
    id: "ts38",
    commands: ["small", "full"],
    pos: "ue",
    text: "Tokome small 38",
    value: "Tokome_small_ue_full_gothic_W68_L38",
    width: 68,
    height: 38,
    critical: false,
    nakaOnly: false,
  },
  ts39: {
    id: "ts39",
    commands: ["small"],
    pos: "naka",
    text: "Tokome small 39 流",
    value: "Tokome_small_naka_full_gothic_W68_L39_流",
    width: 68,
    height: 39,
    critical: false,
    nakaOnly: true,
  },
  s18_3: {
    id: "s18_3",
    commands: ["small"],
    pos: "shita",
    text: "small shita W27 L2&L1",
    value: "small_shita_gothic_W27_L2:7_L1:4_C11",
    width: 27,
    height: 18,
    critical: false,
    nakaOnly: false,
  },
};
export { Templates };
